/**
 * Apex Podcast Co site configuration.
 *
 * Single source for navigation, footer, metadata, and CTA targets. Copy strings
 * live here or in COPY-SPEC-sourced section components, never hardcoded inline
 * beyond non-user-facing labels.
 *
 * PHASE 3 PLACEHOLDER URLS (see PHASE3-PLACEHOLDERS.md). These are documented
 * stand-ins that the Phase 5 GHL sweep swaps for real endpoints. Each is also
 * flagged with a `// TODO: swap to GHL` comment at its use site.
 */

export const siteConfig = {
  name: 'Apex Podcast Co',
  url: 'https://apexpodcast.co',
  defaultTitle: 'Apex Podcast Co. A producer in the room. A network around your show.',
  defaultDescription:
    'Apex Podcast Co is a producer and a network. We tune a show to its host, produce live in every session, and publish into a feed where every Apex show carries the others.',

  // Primary CTA target across the site. TODO: swap to GHL discovery calendar URL
  // (master sub-account QRzW1cp8gNa31VJDILvJ). Placeholder per Phase 3 strategy.
  discoveryUrl: 'https://apexpodcast.co/discovery-call',

  // Partner program. TODO: swap to GHL affiliate signup / portal URLs.
  partnerEnrollUrl: 'https://apexpodcast.co/partner-portal',

  // Affiliate program. 10% on Apex SKUs, 60-day cookie window (2026-06-14 lock).
  // TODO: swap to the live GHL Affiliate Manager signup URL once Brett builds the
  // campaign in the morning (campaigns affil_apex_firstepisode / _weeklyshow / _mtl).
  affiliateSignupUrl: 'https://apexpodcast.co/affiliate',

  // GHL checkout links (Stripe lives inside GHL Payments). These are documented
  // placeholders. TODO: swap to the real GHL checkout URLs generated by Brett's
  // 2026-06-15 product-load runbook. Append ?am_id=<affiliateId> for affiliate
  // attribution once the Affiliate Manager campaign is live.
  checkout: {
    firstEpisode: 'https://apexpodcast.co/checkout/your-first-episode', // TODO: real GHL checkout
    weeklyShow: 'https://apexpodcast.co/checkout/your-weekly-show', // TODO: real GHL checkout
    license: 'https://apexpodcast.co/checkout/multi-tenant-pipeline-license', // TODO: real GHL checkout (tokenized per licensee after NDA)
  },

  email: {
    brett: 'brett@apexpodcast.co',
    randy: 'randy@apexpodcast.co',
    partners: 'partners@apexpodcast.co',
    press: 'press@apexpodcast.co',
  },

  // External properties
  transistorUrl: 'https://apexpodcast.co/listen', // TODO: swap to real Transistor Apex Podcast Network feed URL
  pentatypeUrl: 'https://pentatype.com',
  podcastNetworkUrl: 'https://podcastnetwork.org',

  // "The Apex Podcast" listen targets. TODO: swap to real show URLs (Spotify,
  // Apple Podcasts, Transistor all-platforms page). Placeholders per Phase 3 strategy.
  listen: {
    spotify: 'https://apexpodcast.co/listen', // TODO: real Spotify show URL
    apple: 'https://apexpodcast.co/listen', // TODO: real Apple Podcasts URL
    anywhere: 'https://apexpodcast.co/listen', // TODO: real all-platforms / RSS page
  },
} as const

/**
 * Routes that actually exist in the current build. Next.js prefetches in-viewport
 * links by default; prefetching a route that is not built yet returns a 404 and
 * shows up as a console error. SmartLink consults this set and only prefetches
 * live routes. As each phase lands, add its routes here (one place to maintain).
 */
export const liveRoutes: ReadonlySet<string> = new Set([
  '/',
  // CCM-mirrored page set (2026-06-16 redesign)
  '/how-it-works/',
  '/subscription/',
  '/portfolio/',
  '/case-studies/',
  '/case-studies/the-apex-podcast/',
  '/case-studies/sweeter-after-difficulty/',
  '/case-studies/the-russ-laggan-podcast/',
  '/case-studies/winning-twice/',
  '/resources/',
  '/about/',
  // Phase 2
  '/work/',
  '/work/austin-cheviron/',
  '/work/russ-laggan/',
  '/services/',
  '/your-first-episode/',
  '/your-weekly-show/',
  '/multi-tenant-pipeline-license/',
  // Phase 3
  '/network/',
  '/partners/',
  '/affiliate/',
  '/contact/',
  '/legal/privacy/',
  '/legal/terms/',
  // Phase 3.5 host press-kit pages (cleared named clients only)
  '/russ-laggan/',
  '/austin-cheviron/',
])

export function isLiveRoute(href: string): boolean {
  return liveRoutes.has(href)
}

/** Primary navigation. Mirrors the CCM page set (2026-06-16 redesign). */
export const primaryNav: { label: string; href: string; children?: { label: string; href: string }[] }[] = [
  { label: 'How It Works', href: '/how-it-works/' },
  { label: 'Subscription', href: '/subscription/' },
  { label: 'Portfolio', href: '/portfolio/' },
  { label: 'Case Studies', href: '/case-studies/' },
]

/** Footer link columns. */
export const footerSiteLinks = [
  { label: 'How It Works', href: '/how-it-works/' },
  { label: 'Subscription', href: '/subscription/' },
  { label: 'Portfolio', href: '/portfolio/' },
  { label: 'Case Studies', href: '/case-studies/' },
  { label: 'Liner Notes', href: '/resources/' },
  { label: 'Network', href: '/network/' },
  { label: 'About', href: '/about/' },
]
